export default function TermsPage() {
  return (
    <main className="min-h-screen bg-neutral-900 text-red-100 px-6 py-20 text-lg">
      <div className="max-w-3xl mx-auto space-y-6">
        <h1 className="text-3xl font-bold text-center text-red-500">Terms & Privacy</h1>

        <h2 className="text-2xl font-semibold text-red-400">1. Usage Terms</h2>
        <p>
          TalkToDevil is an entertainment platform designed for satirical conversation, dark humor, and fictional interaction.
          By using this site, you agree not to submit harmful, illegal, or abusive content.
        </p>

        <h2 className="text-2xl font-semibold text-red-400">2. Privacy Policy</h2>
        <p>
          We do not collect names, emails, or IP addresses. All interactions are anonymous by default and are used solely to enhance the experience.
          Messages may be displayed publicly on the Wall if you choose to share them.
        </p>

        <h2 className="text-2xl font-semibold text-red-400">3. AI Responses</h2>
        <p>
          All responses are generated by artificial intelligence and are entirely fictional. They are not meant to be taken as advice,
          guidance, or factual information. Use discretion, and don’t take the Devil too seriously.
        </p>

        <h2 className="text-2xl font-semibold text-red-400">4. Changes</h2>
        <p>
          These terms may be updated at any time without notice. By continuing to use TalkToDevil, you agree to any updated policies.
        </p>

        <h2 className="text-2xl font-semibold text-red-400">5. BoredAtWork Universe</h2>
        <p>
          TalkToDevil is part of the BoredAtWork Universe — a collection of AI-driven platforms for mischief, reflection, and fun.
          Other experiences include Confessly, AskTheDevil, TalkToGod, TalkToBuddha, and DreamDecoder. All apps are fictional and intended purely for entertainment.
        </p>
      </div>
    </main>
  );
}
